hw_quotes/hw_quotes/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("quotes.urls")),
    path("users/", include("users.urls")), 
]

hw_quotes/quotes/urls.py
from django.urls import path

from . import views

app_name = 'quotes'

urlpatterns = [
    path('', views.main, name="root"),
    path('author/<str:author_id>/', views.author_detail, name='author_detail'),
    path("quotes/", views.main, name="quotes"),
    path("quotes/edit/<int:quote_id>/", views.edit_quote, name="edit_quote"),
    path("quotes/remove/<int:quote_id>", views.delete_quote, name="remove"),
    path('<int:page>', views.main, name="root_paginate"),
    path("login/", views.login, name="SignIn"),
    path('tag/<str:tag>/', views.tag_quotes, name='tag_quotes'),
    path('add_author/', views.add_author, name='add_author'),
    path('add_quote/', views.add_quote, name='add_quote'),
]

hw_quotes/users/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,
)

from .forms import LoginForm
from .views import RegisterView, ResetPasswordView

app_name = "users"

urlpatterns = [
    path("signup/", RegisterView.as_view(), name="register"),
    path(
        "signin/",
        LoginView.as_view(
            template_name="users/signin.html",
            authentication_form=LoginForm,
            redirect_authenticated_user=True,
        ),
        name="login",
    ),
    path(
        "logout/", LogoutView.as_view(template_name="users/logout.html"), name="logout"
    ),
    path("reset-password/", ResetPasswordView.as_view(), name="password_reset"),
    path(
        "reset-password/done/",
        PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"),
        name="password_reset_done",
    ),
    path(
        "reset-password/confirm/<uidb64>/<token>/",
        PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html",
            success_url="/users/reset-password/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset-password/complete/",
        PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
]

hw_quotes/quotes/models.py
from django.db import models
from django.contrib.auth.models import User


class Author(models.Model):
    fullname = models.CharField(max_length=100)
    born_date = models.CharField(max_length=100)
    born_location = models.CharField(max_length=100)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.fullname


class Tag(models.Model):
    name = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.name


class Quote(models.Model):
    quote = models.TextField()
    tags = models.ManyToManyField(Tag)
    author = models.ForeignKey(
        Author, on_delete=models.CASCADE, default=None, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=2)

hw_quotes/quotes/forms.py
from django.forms import ModelForm, CharField, TextInput, SelectMultiple
from .models import Author, Quote, Tag
from django import forms


class AuthorForm(ModelForm):
    class Meta:
        model = Author
        fields = ["fullname", "born_date", "born_location", "description"]
        widgets = {
            'fullname': TextInput(attrs={"class": "form-control"}),
            'born_date': TextInput(attrs={"class": "form-control"}),
            'born_location': TextInput(attrs={"class": "form-control"}),
            'description': TextInput(attrs={"class": "form-control"}),
        }


class QuoteForm(ModelForm):
    class Meta:
        model = Quote
        fields = ["quote", "tags", "author"]
        widgets = {
            'quote': TextInput(attrs={"class": "form-control"}),
            'tags': SelectMultiple(attrs={"class": "form-control"}),
        }

hw_quotes/quotes/views.py
import os
from pipes import quote
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.db.models import Count

from django.core.paginator import Paginator

from quotes.forms import AuthorForm, QuoteForm
from .models import Quote, Author, Tag

# Create your views here.


def main(request, page=1):
    top_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    quotes = Quote.objects.all()
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.get_page(page)

    return render(request, 'quotes/index.html', context={'quotes': quotes_on_page, 'top_tags': top_tags})


def get_all_tags():
    return Tag.objects.all()


def author_detail(request, author_id):
    top_tags = Tag.objects.annotate(
        num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    author = Author.objects.get(id=author_id)
    return render(request, 'quotes/author_detail.html', {'author': author, 'top_tags': top_tags})


def tag_quotes(request, tag):
    top_tags = Tag.objects.annotate(num_quotes=Count('quote')).order_by('-num_quotes')[:10]
    quotes_with_tag = Quote.objects.filter(tags__name=tag)
    return render(request, 'quotes/tag_quotes.html', context={'quotes': quotes_with_tag, 'tag': tag, 'top_tags': top_tags})


@login_required
def add_author(request):
    form = AuthorForm(instance=Author())
    if request.method == "POST":
        form = AuthorForm(request.POST, instance=Author())
        if form.is_valid():
            author = form.save(commit=False)
            author.user = request.user
            author.save()
            return redirect(to="quotes:root")
    return render(
        request,
        "quotes/add_author.html",
        context={"title": "Web 10 hw!", "form": form}
    )


@login_required
def add_quote(request):
    form = QuoteForm(instance=Quote())
    if request.method == "POST":
        form = QuoteForm(request.POST, instance=Quote())
        if form.is_valid():
            quote = form.save(commit=False)
            quote.user = request.user
            quote.save()
            selected_tags = request.POST.getlist('tags')
            quote.tags.set(selected_tags)
            return redirect(to="quotes:root")

    return render(
        request,
        "quotes/add_quote.html",
        context={"title": "Web 10 hw!", "form": form, "tags": get_all_tags()}
    )

@login_required
def logined_quotes(request, page=1):
    quotes = Quote.objects.filter(user=request.user).all()
    per_page = 10
    paginator = Paginator(quotes, per_page)
    quotes_on_page = paginator.get_page(page)
    return render(request, 'quotes/index.html', context={"title": "Web 10 hw!", 'quotes': quotes_on_page})


@login_required
def delete_quote(request, quote_id):
    quote = get_object_or_404(Quote, id=quote_id)

    if quote.user == request.user:
        if request.method == "POST":
            quote.delete()
            return redirect('quotes:quote_list')

        return render(request, 'quotes/index.html', {'quote': quote})
    else:

        return redirect('quotes:quote_list')


@login_required
def edit_quote(request, quote_id):
    quote = get_object_or_404(Quote, id=quote_id)
    if quote.user == request.user:
        if request.method == "POST":
            # form = QuoteForm(request.POST, instance=quote)
            form = QuoteForm(request.POST or None, instance=quote)
            # if form.is_valid():
            if request.method == "POST" and form.is_valid():
                form.save()
                return redirect(to="quotes:root")
        else:
            form = QuoteForm(instance=quote)

        return render(request, 'quotes/edit_quote.html', {'form': form, 'quote': quote})
    else:
        return redirect('quotes:quote_list')


def login(request):
    return render(request, "user/signin.html", context={"title": "Web 10 hw!"})


def register(request):
    return render(
        request, "user/signup.html", context={"title": "Web 10 hw!"}
    )
# def main(request, page=1):
#     db = get_postgresql(DATABASES)
#     quotes = db.quotes.find()
#     per_page = 10
#     paginator = Paginator(list(quotes), per_page)
#     quotes_on_page = paginator.page(page)
#     return render(request, 'quotes/index.html', context={})
#     return render(request, 'quotes/index.html', context={'quotes': quotes_on_page})

hw_quotes/quotes/templates/quotes/add_author.html
{% extends "quotes/base.html" %} {% block content %}
<h1>Add Author</h1>
<form
  action="{% url 'quotes:add_author' %}"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Full Name</label>
    {{form.fullname}}
  </div>
  <div class="mb-3">
    <label class="form-label">Born Date</label>
    {{form.born_date}}
  </div>
  <div class="mb-3">
    <label class="form-label">Born location</label>
    {{form.born_location}}
  </div>
  <div class="mb-3">
    <label class="form-label">Dscription</label>
    {{form.description}}
  </div>

  <button type="submit" class="btn btn-primary">Upload</button>
</form>

{% endblock %}

hw_quotes/quotes/templates/quotes/add_quote.html
{% extends "quotes/base.html" %} {% block content %}
<h1>Add Quote</h1>
<form
  action="{% url 'quotes:add_quote' %}"
  method="post"
  enctype="multipart/form-data"
>
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Quote</label>
    {{ form.quote }}
  </div>
  <div class="mb-3">
    <label class="form-label">Author</label>
    {{ form.author }}
  </div>
  <div class="mb-3">
    <h2>Tags:</h2>
    {{ form.tags }}
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

hw_quotes/quotes/templates/quotes/author_detail.html
{% extends 'quotes/base.html' %} {% block content %}
<div class="row">
  <div class="col-md-8">
    <h1>Author: {{ author.fullname }}</h1>
    <p>Birth Date: {{ author.born_date }}</p>
    <p>Biography: {{ author.description }}</p>
    <h2>Quotes by {{ author.fullname }}</h2>
    {% for quote in author.quote_set.all %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text"> {{ quote.quote }} </span>
      <div class="tags">
        Tags: {% for tag in quote.tags.all %}
        <a class="tag" href="/tag/{{ tag }}">{{ tag.name }}</a>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<nav>
  <ul class="pager">
    <li class="previous">
      <a class="{% if not quotes.has_previous %}disabled{% endif %}" href="/">
        <span aria-hidden="true">←</span> Back
      </a>
    </li>
  </ul>
</nav>
{% endblock %} {% block left_sidebar %}
<h3>Top 10 Tags</h3>
<ul>
  {% for tag in top_tags %}
  <li><a href="{% url 'quotes:tag_quotes' tag.name %}">{{ tag.name }}</a></li>
  {% endfor %}
</ul>
{% endblock %}

hw_quotes/quotes/templates/quotes/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-skalable=no, initial-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatable" content="ie=edge" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'quotes/style.css' %}">
      <div class="row">
          <div class="col-md-3">
            <h3>Top 10 Tags</h3>
            <ul>
              {% for tag in top_tags %}
                <li>
                  <a href="{% url 'quotes:tag_quotes' tag.name %}" class="btn btn-primary">{{ tag.name }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
          <div class="col-md-9">
      <title>Django_hw10</title>
          </head>
          <body>
              <div class="container">
              <div class="row header-box pt-3 m-3">
                  <div class="col-md-8">
                  <h1>
                      <a href="/" style="text-decoration: none">Quotes to Scrape</a>
                  </h1>
                  </div>
                  <div class="col-md-4">
                  <p>
                    {% if user.is_authenticated %}
                      <a href="{% url 'quotes:add_author' %}" class="btn btn-primary">Add Author</a>
                      <a href="{% url 'quotes:add_quote' %}" class="btn btn-primary">Add Quote</a>
                      <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>
                    {% else %}
                      <a href="{% url 'users:register' %}" class="btn btn-primary">SignUp</a>
                      <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                    {% endif %}
                  </p>
                  </div>
              </div>
        {% block content %}
        {% endblock %}
      </div>
      </div>
    </div>
  </body>
</html>

hw_quotes/quotes/templates/quotes/edit_quote.html
{% extends "quotes/base.html" %} {% block content %}
<h1>Edit Quote</h1>
<!-- <form
  action="{% url 'quotes:edit_quote' quote.id %}"
  method="post"
  enctype="multipart/form-data"
> -->
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="mb-3">
    <label class="form-label">Quote</label>
    {{ form.quote }}
  </div>
  <div class="mb-3">
    <label class="form-label">Author</label>
    {{ form.author }}
  </div>
  <div class="mb-3">
    <h2>Tags:</h2>
    {{ form.tags }}
  </div>
  <button type="submit" class="btn btn-primary">Save</button>
</form>
{% endblock %}

hw_quotes/quotes/templates/quotes/index.html
{% extends 'quotes/base.html' %} {% load extract %} {% block content %}
<div class="row">
  <div class="col-md-8">
    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text"> {{quote.quote}} </span>
      <span
        >by
        <small class="author" itemprop="author"
          >{{quote.author.fullname}}</small
        >
        <a href="/author/{{quote.author.id}}">(about)</a>
      </span>
      <div class="tags">
        Tags: {% for tag in quote.tags.all %}
        <a class="tag" href="/tag/{{tag.name}}">{{tag.name}}</a>
        {% endfor %}
      </div>
      {% if user.is_authenticated and user == quote.user %}
      <a href="{% url 'quotes:edit_quote' quote.id %}" class="btn btn-primary"
        >Edit</a
      >
      <a href="{% url 'quotes:remove' quote.id %}" class="btn btn-primary"
        >Delete</a
      >
      {% endif %}
    </div>

    {% endfor %}

    <nav>
      <ul class="pager">
        <li class="previous">
          <a
            class="{% if not quotes.has_previous %} disabled {% endif %}"
            href="{% if quotes.has_previous %} {% url 'quotes:root_paginate' quotes.previous_page_number %} {% else %} # {% endif %}"
          >
            <span aria-hidden="true">←</span> Previous</a
          >
        </li>

        <li class="next">
          <a
            class="{% if not quotes.has_next %} disabled {% endif %}"
            href="{% if quotes.has_next %} {% url 'quotes:root_paginate' quotes.next_page_number %} {% else %} # {% endif %}"
          >
            Next <span aria-hidden="true">→</span></a
          >
        </li>
      </ul>
    </nav>

    <div class="pagination">
      <span class="step-links">
        {% if quotes.has_previous %}
        <a href="{% url 'quotes:root_paginate' 1 %}">&laquo; first</a>
        {% endif %} {% for i in quotes.paginator.page_range %}
        <span class="{% if quotes.number == i %}current{% endif %}">
          <a href="{% url 'quotes:root_paginate' i %}">{{ i }}</a>
        </span>
        {% endfor %} {% if quotes.has_next %}
        <a href="{% url 'quotes:root_paginate' quotes.paginator.num_pages %}"
          >last &raquo;</a
        >
        {% endif %}
      </span>
    </div>
  </div>
</div>
{% endblock %}

hw_quotes/quotes/templates/quotes/login.html
{% extends "quotes/base.html" %} {% block content %}
<form>
  <div class="mb-3">
    <label for="exampleInputEmail1" class="form-label">Email address</label>
    <input
      type="email"
      class="form-control"
      id="exampleInputEmail1"
      aria-describedby="emailHelp"
    />
    <div id="emailHelp" class="form-text">
      We'll never share your email with anyone else.
    </div>
  </div>
  <div class="mb-3">
    <label for="exampleInputPassword1" class="form-label">Password</label>
    <input type="password" class="form-control" id="exampleInputPassword1" />
  </div>
  <div class="mb-3 form-check">
    <input type="checkbox" class="form-check-input" id="exampleCheck1" />
    <label class="form-check-label" for="exampleCheck1">Check me out</label>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

hw_quotes/quotes/templates/quotes/tag_quotes.html
{% extends 'quotes/base.html' %} {% block content %}
<div class="row">
  <div class="col-md-8">
    <h1>Quotes with Tag: {{ tag }}</h1>

    {% for quote in quotes %}
    <div class="quote" itemscope="" itemtype="http://schema.org/CreativeWork">
      <span class="text" itemprop="text"> {{ quote.quote }} </span>
      <div class="tags">
        Tags: {% for tag in quote.tags.all %}
        <a class="tag" href="/tag/{{ tag.name }}">{{ tag.name }}</a>
        {% endfor %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>

<nav>
  <ul class="pager">
    <li class="previous">
      <a class="{% if not quotes.has_previous %}disabled{% endif %}" href="/">
        <span aria-hidden="true">←</span> Back
      </a>
    </li>
  </ul>
</nav>
{% endblock %} {% block left_sidebar %}
<h3>Top 10 Tags</h3>
<ul>
  {% for tag in top_tags %}
  <li><a href="{% url 'quotes:tag_quotes' tag.name %}">{{ tag.name }}</a></li>
  {% endfor %}
</ul>
{% endblock %}